language: csharp
mono: 3.12.0
env: TARGET_LANG=dotnet
sudo: false

matrix:
  include:
    - env: TARGET_LANG=perl
      language: perl
      perl: "5.14"
      install:
        - ( cd $TARGET_LANG; dzil authordeps --missing | cpanm --no-skip-satisfied )
        - ( cd $TARGET_LANG; dzil listdeps --author --missing | cpanm --no-skip-satisfied )

    - env: TARGET_LANG=perl
      language: perl
      perl: "5.20"
      install:
        - ( cd $TARGET_LANG; dzil authordeps --missing | cpanm --no-skip-satisfied )
        - ( cd $TARGET_LANG; dzil listdeps --author --missing | cpanm --no-skip-satisfied )

    - env: TARGET_LANG=java
      language: java
      jdk: oraclejdk8
      before_install:
        # https://github.com/travis-ci/travis-ci/issues/2839
        - export JAVA_HOME="$(/usr/libexec/java_home)"

    - env: TARGET_LANG=javascript
      language: javascript
      node_js: 4.4.1
    - env: TARGET_LANG=javascript
      language: javascript
      node_js: 5.9.0

    - env: TARGET_LANG=go
      language: go
      go: tip

    - env: TARGET_LANG=python
      language: python
      python: "2.7.11"
      install: "pip install -r $TARGET_LANG/requirements.txt"
    - env: TARGET_LANG=python
      language: python
      python: "3.5.1"
      install: "pip install -r $TARGET_LANG/requirements.txt"

    - env: TARGET_LANG=objective-c
      language: objective-c
      os: osx
      osx_image: xcode7
      before_script:
        - brew install jq

    - env: TARGET_LANG=c
      language: c
      compiler: gcc
    - env: TARGET_LANG=c
      language: c
      compiler: clang
    - env: TARGET_LANG=c
      language: c
      os: osx
      osx_image: xcode8.2
      compiler: gcc
      before_script:
        - brew install jq

before_install:
  - export EnableNuGetPackageRestore=true

addons:
  apt:
    packages:
    - jq

before_script:
  - locale

# Simulate non-UTF-8 standard encoding on OS. Should still work
script: "cd $TARGET_LANG; LANG=fr_FR.iso-8859-15 make"

branches:
  only:
    - master
