os: Visual Studio 2015

build_script:
  # dotnet info
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet --verbose build dotnet/Gherkin
  - ps: dotnet --verbose build dotnet/Gherkin.AstGenerator
  - ps: dotnet --verbose build dotnet/Gherkin.TokensGenerator
  - ps: dotnet --verbose build dotnet/Gherkin.Specs
  - ps: dotnet run -f net45 -p dotnet/Gherkin.Specs/
  - ps: dotnet run -f netstandard1.5 -p dotnet/Gherkin.Specs/  
  - ps: Pop-Location

test: off 